### ISSUE TITLE
Please Submit This to Lambda-Packages

### ISSUE THREAD

**Issue by Miserlou** [jDmacD/aws-lambda-pillow#1]
Hey James!

I saw your link to this project on reddit - looks awesome!

It'd be absolutely awesome if we could have this merged with [lambda-packages](/Miserlou/lambda-packages) - there are many Python web apps that use Pillow, so having out-of-the-box support for Pillow on Lambda would be a huge win!

Would you be willing to submit a pull request to lambda-packages? :D

**Comment by jDmacD** [comment]
Hi Rich,
Sure thing. I'll split out the Pillow part of it and submit a pull request. I need a few days to have a look at  lamdba-packages so that I can follow your format.

Could you have a look over my [build script](https://github.com/jDmacD/aws-lambda-pillow/blob/master/aws/ec2/userData.sh) to confirm that it is similar to the methodology you have used?

I'm also working on SVG (Scalable Vector Graphic) support, along with pyCairo and pyGTK, but have run into a few issues with the build on EC2. I've posted a question on the [EC2 forums](https://forums.aws.amazon.com/message.jspa?messageID=706911#706911), which I'm sure no one will ever answer. Any chance you could cast your eye over it?

**Comment by Miserlou** [comment]
Awesome!

The build script looks great to me - feel free to include that in the PR! The manifest format is really really simple, it's just a dictionary with the package name, version, and a path to the archive.

Another thing I've noticed is that it often helps to chmod 755 the .so files, but that may or may not be voodoo. 

Also, is requests necessary? I think that's pure python, so not necessary to package on EC2, but I could be wrong.

That GTK problem looks like a dooooozy. :( Personally, I'd try building all of GTK from scratch using as few yum-dependencies as possible, but it looks like you've already tried that. I've never had much luck combining Amazon and Red Hat repos for exactly this reason. I wish I could be more helpful, but it looks like you're pretty far down the rabbit hole! Maybe you could try doing the actual build on a Red Hat box and then including everything it would need to run in the Lambda environment? Or maybe look at something like [CDE](http://www.pgbovine.net/cde/manual/) for your builds? Those are probably not smart ideas.

**Comment by jDmacD** [comment]
You'll have to bear with me, frankly I'm a Python newbie who has just immigrated from Javascript Land, but it looks pretty straight forward.

I haven't run into any permissions issues as of yet, but I'll add in the chmod for good measure.

I won't include _requests_, _eventlet_ or _simplejson_ in the env pack, they're not necessary for your project.

I'm probably going to deep six the pygtk plan, I don't think it's worth my sanity! Thanks for having a look though. 

In general I'm very interested in Lambda/Python as a scalable image processing platform. If you have any suggestions for other useful image utilities I'd love to hear them.

Check [this](https://serverlesscode.com/post/deploy-scikitlearn-on-lamba/) out. You may want to get in touch with this dude, he seems to be working along the same lines as you.

**Comment by Miserlou** [comment]
I think _eventlet_ and _simplejson_ would be very welcome inclusions, as those are quite common packages in the Python world, so having them available in lambda-packages would be useful for everybody!

W/R/T image processing - I was actually able to have a ton of success with using CDE (linked above) on Lambda (got GCC working, woo), so I bet you'd be able to use CDE to get [ImageMagick](http://www.imagemagick.org/script/index.php) working on Lambda with no problems. ImageMagick can do pretty much everything you'd ever want to with regards to image processing, so I imagine that'd be pretty powerful. Does that make sense?

I've been in touch with Ryan from ServerlessCode.com before - my only qualm about including scikit-learn in lambda-packages is the the resulting archive is ~40M, which is pretty chunky!

**Comment by jDmacD** [comment]
OK. That's done, I think...
Could you [have a look](https://github.com/jDmacD/lambda-packages/tree/master/lambda_packages/Pillow) before I initiate a pull request?

The tar contents:

![pack](https://cloud.githubusercontent.com/assets/6770688/13640341/2bbc83c4-e60c-11e5-92d1-9dfb670ab5aa.PNG)

Is this suitable for your purposes?

**Comment by jDmacD** [comment]
[fulfilled](https://github.com/Miserlou/lambda-packages/pull/2)
